import { THEME } from "./theme";

export const DEFAULT_GLOBAL_LAYOUT_CONFIG = {
  aspectRatio: THEME.canvas.aspectRatio,
  primaryColor: "#C84B31",
  accentColor: "#FAD4C0",
  bgColor: "#ffffff",
  bgPattern: "solid",
  headlineFont: THEME.typography.headline.fontFamily,
  bodyFont: THEME.typography.body.fontFamily,
  textAlign: "left",
  badgeX: THEME.contentZone.x,
  badgeY: THEME.safeArea.top + 24,
  badgeFontSize: 20,
  badgeFont: "Playfair Display",
  badgeColor: "#C84B31",
  badgeText: "",
  headlineX: THEME.contentZone.x,
  headlineY: THEME.contentZone.y,
  headlineFontSize: 92,
  headlineColor: THEME.colors.textPrimary,
  bodyX: THEME.contentZone.x,
  bodyY: 459,
  bodyFontSize: 64,
  bodyColor: THEME.colors.textSecondary,
  dirRectX: THEME.canvas.width / 2,
  dirRectY: 865,
  dirRectWidth: 760,
  dirRectHeight: 340,
  dirRectFill: "#eff6ff",
  dirRectStroke: "#8e5c29",
  dirRectStrokeWidth: 2,
  dirTextX: 200,
  dirTextY: 770,
  dirTextFontSize: 24,
  dirTextColor: "#8e5c29",
  pageNumberX: THEME.chrome.pageNumber.x,
  pageNumberY: THEME.chrome.pageNumber.y,
  pageNumberFontSize: THEME.typography.footer.fontSize,
  pageNumberFont: THEME.typography.footer.fontFamily || "Georgia",
  pageNumberColor: THEME.colors.footer,
  swipeX: THEME.chrome.swipeIndicator.x,
  swipeY: THEME.chrome.swipeIndicator.y,
  swipeFontSize: THEME.typography.footer.fontSize,
  swipeFont: THEME.typography.footer.fontFamily || "Georgia",
  swipeColor: THEME.colors.footer,
  swipeText: "Swipe →",
  followX: THEME.chrome.swipeIndicator.x,
  followY: THEME.chrome.swipeIndicator.y,
  followFontSize: THEME.typography.footer.fontSize,
  followFont: THEME.typography.footer.fontFamily || "Georgia",
  followColor: THEME.colors.footer,
  followText: "Follow for more →",
  showGrid: false,
  snapToGuides: false,
  marginTop: THEME.safeArea.top,
  marginRight: THEME.safeArea.right,
  marginBottom: THEME.safeArea.bottom,
  marginLeft: THEME.safeArea.left,
  gridColumns: 12,
  gutterWidth: 16,
  elementPadding: 16,
  safeAreaMarginTop: THEME.safeArea.top,
  safeAreaMarginBottom: THEME.safeArea.bottom,
  safeAreaMarginLeft: THEME.safeArea.left,
  safeAreaMarginRight: THEME.safeArea.right,
  contentTopClearance: THEME.contentZone.top,
  contentBottomClearance: THEME.contentZone.bottom,
  contentPaddingLeft: THEME.contentZone.paddingLeft,
  contentPaddingRight: THEME.contentZone.paddingRight,
};
