import { THEME } from "./theme";

export const DEFAULT_GLOBAL_LAYOUT_CONFIG = {
  aspectRatio: THEME.canvas.aspectRatio,
  primaryColor: "#C84B31",
  accentColor: "#FAD4C0",
  bgColor: "#ffffff",
  bgPattern: "solid",
  headlineFont: THEME.typography.headline.fontFamily,
  bodyFont: THEME.typography.body.fontFamily,
  textAlign: "left",
  headlineX: THEME.contentZone.x,
  headlineY: THEME.contentZone.y,
  headlineFontSize: 44,
  headlineColor: THEME.colors.textPrimary,
  bodyX: THEME.contentZone.x,
  bodyY: 409,
  bodyFontSize: 30,
  bodyColor: THEME.colors.textSecondary,
  dirRectX: THEME.canvas.width / 2,
  dirRectY: 865,
  dirRectWidth: 760,
  dirRectHeight: 340,
  dirRectFill: "#eff6ff",
  dirRectStroke: "#8e5c29",
  dirRectStrokeWidth: 2,
  dirTextX: 200,
  dirTextY: 770,
  dirTextFontSize: 24,
  dirTextColor: "#8e5c29",
  pageNumberX: THEME.chrome.pageNumber.x,
  pageNumberY: THEME.chrome.pageNumber.y,
  pageNumberFontSize: THEME.typography.footer.fontSize,
  pageNumberColor: THEME.colors.footer,
  swipeX: THEME.chrome.swipeIndicator.x,
  swipeY: THEME.chrome.swipeIndicator.y,
  swipeFontSize: THEME.typography.footer.fontSize,
  swipeColor: THEME.colors.footer,
  swipeText: "Swipe →",
  followX: THEME.chrome.swipeIndicator.x,
  followY: THEME.chrome.swipeIndicator.y,
  followFontSize: THEME.typography.footer.fontSize,
  followColor: THEME.colors.footer,
  followText: "Follow for more →",
  showGrid: false,
  snapToGuides: false,
  marginTop: THEME.safeArea.top,
  marginRight: THEME.safeArea.right,
  marginBottom: THEME.safeArea.bottom,
  marginLeft: THEME.safeArea.left,
  gridColumns: 12,
  gutterWidth: 16,
  elementPadding: 16,
  safeAreaMarginTop: THEME.safeArea.top,
  safeAreaMarginBottom: THEME.safeArea.bottom,
  safeAreaMarginLeft: THEME.safeArea.left,
  safeAreaMarginRight: THEME.safeArea.right,
  contentTopClearance: THEME.contentZone.top,
  contentBottomClearance: THEME.contentZone.bottom,
  contentPaddingLeft: THEME.contentZone.paddingLeft,
  contentPaddingRight: THEME.contentZone.paddingRight,
};
