import React from 'react'

export const CAROUSEL_TEMPLATES = {
  'hook-open': {
    name: 'Hook / Open',
    badge: 'Slide 1 · Scroll-Stopper',
    icon: '🎯',
    description: 'High-impact asymmetric title with highlighter accent block and topic watermark.',
    elements: [
      {
        type: 'badge',
        content: '[ TRACK 01 · SEPIA ]',
        x: 40,
        y: 80,
        width: 160,
        height: 28,
        font: { family: 'monospace', size: 11, weight: 'bold', color: '#8B5E3C' },
        backgroundColor: 'rgba(139, 94, 60, 0.1)',
        borderColor: 'rgba(139, 94, 60, 0.3)',
      },
      {
        type: 'text',
        content: 'Why Did Humans Even Invent Computers?',
        x: 40,
        y: 150,
        width: 460,
        height: 120,
        font: { family: 'Georgia', size: 40, weight: 'bold', color: '#0f172a' },
        align: 'left',
        highlight: true,
        highlightColor: '#D9C7A3',
      },
      {
        type: 'text',
        content: 'Humans have always needed to calculate, track, and remember more than our brains could hold on their own.',
        x: 40,
        y: 310,
        width: 460,
        height: 90,
        font: { family: 'Inter', size: 18, weight: '500', color: '#475569' },
        align: 'left',
        highlight: false,
      },
      {
        type: 'icon',
        icon: 'computer',
        size: 72,
        color: 'rgba(139, 94, 60, 0.25)',
        x: 390,
        y: 450,
        width: 80,
        height: 80,
      },
    ],
    config: {
      background: '#F8F7F4',
      backgroundType: 'dots',
      currentSlideNo: 1,
      totalSlides: 7,
    },
  },

  'concept-explain': {
    name: 'Concept / Explain',
    badge: 'Slide 2-3 · Core Theory',
    icon: '📖',
    description: 'Split container with dedicated technical diagram and structured insight card.',
    elements: [
      {
        type: 'badge',
        content: '[ CORE MECHANISM ]',
        x: 40,
        y: 70,
        width: 150,
        height: 28,
        font: { family: 'monospace', size: 11, weight: 'bold', color: '#1E5FA8' },
        backgroundColor: 'rgba(30, 95, 168, 0.1)',
        borderColor: 'rgba(30, 95, 168, 0.3)',
      },
      {
        type: 'text',
        content: 'The Stored-Program Architecture',
        x: 40,
        y: 110,
        width: 460,
        height: 50,
        font: { family: 'Georgia', size: 30, weight: 'bold', color: '#0f172a' },
        align: 'left',
        highlight: true,
        highlightColor: '#A9D0F5',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FFFFFF',
        stroke: '1.5px solid #1E5FA8',
        x: 40,
        y: 180,
        width: 460,
        height: 180,
        borderRadius: 16,
        opacity: 0.95,
      },
      {
        type: 'icon',
        icon: 'computer',
        size: 64,
        color: '#1E5FA8',
        x: 238,
        y: 205,
        width: 64,
        height: 64,
      },
      {
        type: 'text',
        content: 'CPU (Control Unit + ALU) ⟷ Memory (RAM)',
        x: 60,
        y: 285,
        width: 420,
        height: 40,
        font: { family: 'monospace', size: 13, weight: 'bold', color: '#1E5FA8' },
        align: 'center',
        highlight: false,
      },
      {
        type: 'text',
        content: 'Instructions and data live in the exact same memory space — allowing programs to modify their own behavior dynamically.',
        x: 40,
        y: 380,
        width: 460,
        height: 80,
        font: { family: 'Inter', size: 16, weight: 'normal', color: '#334155' },
        align: 'left',
        highlight: false,
      },
    ],
    config: {
      background: '#FFFFFF',
      backgroundType: 'gradient',
      currentSlideNo: 2,
      totalSlides: 7,
    },
  },

  'process-flow': {
    name: 'Process / Flow',
    badge: 'Slide 3-4 · Pipeline Stepper',
    icon: '🔄',
    description: '3-stage directional workflow with numbered badge pills and connecting arrows.',
    elements: [
      {
        type: 'text',
        content: 'The Fetch-Decode-Execute Cycle',
        x: 40,
        y: 80,
        width: 460,
        height: 50,
        font: { family: 'Georgia', size: 28, weight: 'bold', color: '#0f172a' },
        align: 'center',
        highlight: true,
        highlightColor: '#B6E6CE',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#F0FDF4',
        stroke: '1.5px solid #1F8A5F',
        x: 40,
        y: 160,
        width: 135,
        height: 140,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '01\nFETCH\nGet instruction from RAM',
        x: 45,
        y: 180,
        width: 125,
        height: 100,
        font: { family: 'Inter', size: 13, weight: 'bold', color: '#1F8A5F' },
        align: 'center',
      },
      {
        type: 'icon',
        icon: 'arrow',
        size: 28,
        color: '#1F8A5F',
        x: 185,
        y: 215,
        width: 28,
        height: 28,
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#F0FDF4',
        stroke: '1.5px solid #1F8A5F',
        x: 220,
        y: 160,
        width: 135,
        height: 140,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '02\nDECODE\nBreak opcode into micro-ops',
        x: 225,
        y: 180,
        width: 125,
        height: 100,
        font: { family: 'Inter', size: 13, weight: 'bold', color: '#1F8A5F' },
        align: 'center',
      },
      {
        type: 'icon',
        icon: 'arrow',
        size: 28,
        color: '#1F8A5F',
        x: 365,
        y: 215,
        width: 28,
        height: 28,
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#F0FDF4',
        stroke: '1.5px solid #1F8A5F',
        x: 400,
        y: 160,
        width: 100,
        height: 140,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '03\nEXECUTE\nRun in ALU',
        x: 405,
        y: 180,
        width: 90,
        height: 100,
        font: { family: 'Inter', size: 13, weight: 'bold', color: '#1F8A5F' },
        align: 'center',
      },
      {
        type: 'text',
        content: 'This loop executes billions of times every single second inside your processor.',
        x: 40,
        y: 340,
        width: 460,
        height: 60,
        font: { family: 'Inter', size: 16, weight: '500', color: '#475569' },
        align: 'center',
      },
    ],
    config: {
      background: '#FFFFFF',
      backgroundType: 'dots',
      currentSlideNo: 3,
      totalSlides: 7,
    },
  },

  'comparison': {
    name: 'Comparison',
    badge: 'Slide 4 · Dual-Column Split',
    icon: '⚖️',
    description: 'Split screen 50/50 comparison contrasting two distinct approaches.',
    elements: [
      {
        type: 'text',
        content: 'Imperative vs Declarative',
        x: 40,
        y: 70,
        width: 460,
        height: 40,
        font: { family: 'Georgia', size: 30, weight: 'bold', color: '#0f172a' },
        align: 'center',
        highlight: true,
        highlightColor: '#FBD38D',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FEF2F2',
        stroke: '1.5px solid #DC2626',
        x: 35,
        y: 140,
        width: 220,
        height: 270,
        borderRadius: 14,
      },
      {
        type: 'text',
        content: '❌ Imperative\n\n• Explicit step-by-step\n• Focuses on "HOW"\n• Manual state tracking\n• Prone to side-effects',
        x: 45,
        y: 155,
        width: 200,
        height: 230,
        font: { family: 'Inter', size: 14, weight: 'normal', color: '#7F1D1D' },
        align: 'left',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#F0FDF4',
        stroke: '1.5px solid #16A34A',
        x: 285,
        y: 140,
        width: 220,
        height: 270,
        borderRadius: 14,
      },
      {
        type: 'text',
        content: '✅ Declarative\n\n• Specifies target result\n• Focuses on "WHAT"\n• Framework manages state\n• Clean & composable',
        x: 295,
        y: 155,
        width: 200,
        height: 230,
        font: { family: 'Inter', size: 14, weight: 'normal', color: '#14532D' },
        align: 'left',
      },
    ],
    config: {
      background: '#FFFFFF',
      backgroundType: 'solid',
      currentSlideNo: 4,
      totalSlides: 7,
    },
  },

  'real-world': {
    name: 'Real-World Moment',
    badge: 'Slide 5 · Terminal / IDE Card',
    icon: '📟',
    description: 'Dark-mode terminal window with macOS controls and syntax snippet.',
    elements: [
      {
        type: 'badge',
        content: '[ PRODUCTION CASE ]',
        x: 40,
        y: 70,
        width: 160,
        height: 28,
        font: { family: 'monospace', size: 11, weight: 'bold', color: '#F2A65A' },
        backgroundColor: 'rgba(242, 166, 90, 0.15)',
        borderColor: 'rgba(242, 166, 90, 0.4)',
      },
      {
        type: 'text',
        content: 'Real-World Production Moment',
        x: 40,
        y: 110,
        width: 460,
        height: 45,
        font: { family: 'Georgia', size: 28, weight: 'bold', color: '#0f172a' },
        align: 'left',
        highlight: true,
        highlightColor: '#F2A65A',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#1E1E2E',
        stroke: '1.5px solid rgba(255,255,255,0.1)',
        x: 40,
        y: 170,
        width: 460,
        height: 220,
        borderRadius: 14,
      },
      {
        type: 'text',
        content: '$ curl -v https://api.prod.system/v1/health\n> GET /v1/health HTTP/2\n> Host: api.prod.system\n< HTTP/2 200 OK\n< content-type: application/json\n{"status":"healthy","latency_ms":12}',
        x: 55,
        y: 195,
        width: 430,
        height: 180,
        font: { family: 'monospace', size: 12, weight: '500', color: '#A6E3A1' },
        align: 'left',
      },
      {
        type: 'text',
        content: '💡 In production, observing protocol headers directly isolates connection leaks before touching code.',
        x: 40,
        y: 410,
        width: 460,
        height: 60,
        font: { family: 'Inter', size: 15, weight: '500', color: '#334155' },
        align: 'left',
      },
    ],
    config: {
      background: '#F8F7F4',
      backgroundType: 'dots',
      currentSlideNo: 5,
      totalSlides: 7,
    },
  },

  'recap-close': {
    name: 'Quick Recap',
    badge: 'Slide 6 · Summary Checklist',
    icon: '✅',
    description: 'Scannable 4-point checklist card with circular tick icons.',
    elements: [
      {
        type: 'badge',
        content: '[ SUMMARY ]',
        x: 40,
        y: 70,
        width: 120,
        height: 28,
        font: { family: 'monospace', size: 11, weight: 'bold', color: '#1E5FA8' },
        backgroundColor: 'rgba(30, 95, 168, 0.1)',
        borderColor: 'rgba(30, 95, 168, 0.3)',
      },
      {
        type: 'text',
        content: 'Quick Recap',
        x: 40,
        y: 110,
        width: 460,
        height: 45,
        font: { family: 'Georgia', size: 32, weight: 'bold', color: '#0f172a' },
        align: 'left',
        highlight: true,
        highlightColor: '#A9D0F5',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FFFFFF',
        stroke: '1px solid #E2E8F0',
        x: 40,
        y: 170,
        width: 460,
        height: 240,
        borderRadius: 16,
      },
      {
        type: 'text',
        content: '✓  Why humans needed calculation machines\n✓  Tally sticks, abacus, and gears\n✓  The breakthrough of stored programs\n✓  Why this architecture powers your phone today',
        x: 60,
        y: 200,
        width: 420,
        height: 180,
        font: { family: 'Inter', size: 16, weight: '500', color: '#1E293B' },
        align: 'left',
      },
    ],
    config: {
      background: '#FFFFFF',
      backgroundType: 'gradient',
      currentSlideNo: 6,
      totalSlides: 7,
    },
  },

  'next-up': {
    name: 'Next Up / Closing CTA',
    badge: 'Slide 7 · Brand Seal & Closer',
    icon: '🏵️',
    description: 'Official circular SWE brand seal + upcoming post preview card + follow CTA.',
    elements: [
      {
        type: 'logo',
        x: 235,
        y: 80,
        width: 70,
        height: 70,
      },
      {
        type: 'text',
        content: 'SWE Notebook · Zero to Hero',
        x: 40,
        y: 160,
        width: 460,
        height: 30,
        font: { family: 'monospace', size: 13, weight: 'bold', color: '#1E5FA8' },
        align: 'center',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FFFFFF',
        stroke: '1.5px solid #1E5FA8',
        x: 40,
        y: 210,
        width: 460,
        height: 160,
        borderRadius: 16,
      },
      {
        type: 'text',
        content: 'COMING UP NEXT',
        x: 60,
        y: 230,
        width: 420,
        height: 25,
        font: { family: 'monospace', size: 12, weight: 'bold', color: '#64748B' },
        align: 'center',
      },
      {
        type: 'text',
        content: 'The Minds Before Computers Existed',
        x: 60,
        y: 260,
        width: 420,
        height: 60,
        font: { family: 'Georgia', size: 24, weight: 'bold', color: '#0F172A' },
        align: 'center',
        highlight: true,
        highlightColor: '#A9D0F5',
      },
      {
        type: 'text',
        content: '🔖 Save this post & Follow for daily SWE visual breakdowns!',
        x: 40,
        y: 400,
        width: 460,
        height: 40,
        font: { family: 'Inter', size: 15, weight: 'bold', color: '#1E5FA8' },
        align: 'center',
      },
    ],
    config: {
      background: '#F8F7F4',
      backgroundType: 'gradient-radial',
      currentSlideNo: 7,
      totalSlides: 7,
      footer: {
        show: true,
        showSlideNumber: true,
        showSwipe: false,
        font: { family: 'sans-serif', size: 11, color: '#64748b' },
      },
    },
  },

  'timeline-ribbon': {
    name: 'Timeline Ribbon',
    badge: 'Slide 4-5 · Milestones',
    icon: '📅',
    description: 'Continuous chronological milestone line with event marker nodes.',
    elements: [
      {
        type: 'badge',
        content: '[ TIMELINE ]',
        x: 40,
        y: 70,
        width: 120,
        height: 28,
        font: { family: 'monospace', size: 11, weight: 'bold', color: '#1E5FA8' },
        backgroundColor: 'rgba(30, 95, 168, 0.1)',
        borderColor: 'rgba(30, 95, 168, 0.3)',
      },
      {
        type: 'text',
        content: 'Evolution of Modern Computing',
        x: 40,
        y: 110,
        width: 460,
        height: 50,
        font: { family: 'Georgia', size: 28, weight: 'bold', color: '#0f172a' },
        align: 'left',
        highlight: true,
        highlightColor: '#A9D0F5',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: 'rgba(30, 95, 168, 0.15)',
        stroke: 'none',
        x: 60,
        y: 260,
        width: 420,
        height: 4,
        borderRadius: 2,
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#1E5FA8',
        stroke: '2px solid #FFFFFF',
        x: 90,
        y: 254,
        width: 16,
        height: 16,
        borderRadius: 8,
      },
      {
        type: 'text',
        content: '1837\nAnalytical Engine',
        x: 50,
        y: 280,
        width: 100,
        height: 60,
        font: { family: 'Inter', size: 11, weight: 'bold', color: '#1E293B' },
        align: 'center',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#1E5FA8',
        stroke: '2px solid #FFFFFF',
        x: 220,
        y: 254,
        width: 16,
        height: 16,
        borderRadius: 8,
      },
      {
        type: 'text',
        content: '1945\nENIAC & Von Neumann',
        x: 170,
        y: 280,
        width: 120,
        height: 60,
        font: { family: 'Inter', size: 11, weight: 'bold', color: '#1E293B' },
        align: 'center',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#1E5FA8',
        stroke: '2px solid #FFFFFF',
        x: 350,
        y: 254,
        width: 16,
        height: 16,
        borderRadius: 8,
      },
      {
        type: 'text',
        content: '1971\nMicroprocessors',
        x: 300,
        y: 280,
        width: 110,
        height: 60,
        font: { family: 'Inter', size: 11, weight: 'bold', color: '#1E293B' },
        align: 'center',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#0284C7',
        stroke: '2px solid #FFFFFF',
        x: 440,
        y: 254,
        width: 16,
        height: 16,
        borderRadius: 8,
      },
      {
        type: 'text',
        content: '2025+\nAutonomous AI',
        x: 390,
        y: 280,
        width: 110,
        height: 60,
        font: { family: 'Inter', size: 11, weight: 'bold', color: '#0284C7' },
        align: 'center',
      },
      {
        type: 'text',
        content: 'Each breakthrough in computing reduced mechanical friction and amplified human cognition.',
        x: 40,
        y: 380,
        width: 460,
        height: 60,
        font: { family: 'Inter', size: 14, weight: '500', color: '#475569' },
        align: 'left',
      },
    ],
    config: {
      background: '#FFFFFF',
      backgroundType: 'dots',
      currentSlideNo: 5,
      totalSlides: 7,
    },
  },

  'architecture-blueprint': {
    name: 'Architecture Blueprint',
    badge: 'Slide 3-5 · System Design',
    icon: '🏗️',
    description: 'Clean system design nodes with directional request/response flow.',
    elements: [
      {
        type: 'badge',
        content: '[ SYSTEM BLUEPRINT ]',
        x: 40,
        y: 70,
        width: 160,
        height: 28,
        font: { family: 'monospace', size: 11, weight: 'bold', color: '#0E8FA0' },
        backgroundColor: 'rgba(14, 143, 160, 0.1)',
        borderColor: 'rgba(14, 143, 160, 0.3)',
      },
      {
        type: 'text',
        content: 'Event-Driven Pipeline Architecture',
        x: 40,
        y: 110,
        width: 460,
        height: 50,
        font: { family: 'Georgia', size: 28, weight: 'bold', color: '#0f172a' },
        align: 'left',
        highlight: true,
        highlightColor: '#A9E7EE',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FFFFFF',
        stroke: '1.5px solid #0E8FA0',
        x: 40,
        y: 170,
        width: 120,
        height: 90,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '🌐\nAPI Gateway',
        x: 45,
        y: 185,
        width: 110,
        height: 60,
        font: { family: 'Inter', size: 12, weight: 'bold', color: '#0f172a' },
        align: 'center',
      },
      {
        type: 'icon',
        icon: 'arrow',
        size: 24,
        color: '#0E8FA0',
        x: 170,
        y: 205,
        width: 24,
        height: 24,
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FFFFFF',
        stroke: '1.5px solid #0E8FA0',
        x: 205,
        y: 170,
        width: 130,
        height: 90,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '⚙️\nWorker Queue',
        x: 210,
        y: 185,
        width: 120,
        height: 60,
        font: { family: 'Inter', size: 12, weight: 'bold', color: '#0f172a' },
        align: 'center',
      },
      {
        type: 'icon',
        icon: 'arrow',
        size: 24,
        color: '#0E8FA0',
        x: 345,
        y: 205,
        width: 24,
        height: 24,
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FFFFFF',
        stroke: '1.5px solid #0E8FA0',
        x: 380,
        y: 170,
        width: 120,
        height: 90,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '🗃️\nPrimary DB',
        x: 385,
        y: 185,
        width: 110,
        height: 60,
        font: { family: 'Inter', size: 12, weight: 'bold', color: '#0f172a' },
        align: 'center',
      },
      {
        type: 'text',
        content: 'Decoupling ingress from batch processing prevents thread pool starvation under bursty traffic.',
        x: 40,
        y: 300,
        width: 460,
        height: 60,
        font: { family: 'Inter', size: 14, weight: '500', color: '#334155' },
        align: 'left',
      },
    ],
    config: {
      background: '#FFFFFF',
      backgroundType: 'grid',
      currentSlideNo: 3,
      totalSlides: 7,
    },
  },

  'matrix-replace': {
    name: 'Matrix Replace',
    badge: 'Slide 4 · Transformation',
    icon: '🔄',
    description: '2-column role-to-AI replacement matrix with arrows and indicator icons.',
    elements: [
      {
        type: 'badge',
        content: '[ PARADIGM SHIFT ]',
        x: 40,
        y: 70,
        width: 160,
        height: 28,
        font: { family: 'monospace', size: 11, weight: 'bold', color: '#C84B31' },
        backgroundColor: 'rgba(200, 75, 49, 0.1)',
        borderColor: 'rgba(200, 75, 49, 0.3)',
      },
      {
        type: 'text',
        content: 'How AI Upgrades SWE Workflows',
        x: 40,
        y: 110,
        width: 460,
        height: 50,
        font: { family: 'Georgia', size: 28, weight: 'bold', color: '#0f172a' },
        align: 'left',
        highlight: true,
        highlightColor: '#FAD4C0',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#FEF2F2',
        stroke: '1px solid #FECACA',
        x: 40,
        y: 170,
        width: 200,
        height: 180,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '❌ Legacy Approach\n\n• Hand-written boilerplate\n• Manual regex parsing\n• Fragile mock fixtures\n• 4h troubleshooting',
        x: 50,
        y: 185,
        width: 180,
        height: 150,
        font: { family: 'Inter', size: 12, weight: '500', color: '#991B1B' },
        align: 'left',
      },
      {
        type: 'shape',
        shape: 'rectangle',
        fill: '#F0FDF4',
        stroke: '1px solid #BBF7D0',
        x: 300,
        y: 170,
        width: 200,
        height: 180,
        borderRadius: 12,
      },
      {
        type: 'text',
        content: '✅ Agentic Workflow\n\n• Intent-driven code gen\n• AST semantic transforms\n• Auto-derived unit suites\n• 30s root-cause trace',
        x: 310,
        y: 185,
        width: 180,
        height: 150,
        font: { family: 'Inter', size: 12, weight: '500', color: '#166534' },
        align: 'left',
      },
      {
        type: 'text',
        content: 'The leverage shift: You evolve from typing syntax to validating architecture and edge-case contracts.',
        x: 40,
        y: 380,
        width: 460,
        height: 60,
        font: { family: 'Inter', size: 14, weight: '500', color: '#334155' },
        align: 'left',
      },
    ],
    config: {
      background: '#FFFFFF',
      backgroundType: 'solid',
      currentSlideNo: 4,
      totalSlides: 7,
    },
  },
}

export default function SlideTemplates({ onLoadTemplate, trackColor = { primary: '#1E5FA8', accent: '#A9D0F5' } }) {
  return (
    <div className="flex flex-col gap-4 font-sans select-none">
      <div>
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-1">
          Carousel Templates
        </h3>
        <p className="text-[11px] text-slate-500">
          Load production-ready slide LayoutCategorys with one click.
        </p>
      </div>

      <div className="flex flex-col gap-2.5">
        {Object.entries(CAROUSEL_TEMPLATES).map(([key, template]) => (
          <button
            key={key}
            type="button"
            className="flex items-start gap-3 p-3 rounded-xl bg-white/5 hover:bg-white/10 text-slate-200 transition-all border border-white/5 hover:border-cyan-400/40 text-left group cursor-pointer"
            onClick={() => onLoadTemplate(template)}
          >
            <span className="text-xl p-2 rounded-lg bg-black/40 border border-white/10">
              {template.icon}
            </span>
            <div className="flex flex-col flex-1">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-slate-100 group-hover:text-cyan-300">
                  {template.name}
                </span>
              </div>
              <span className="text-[10px] font-mono text-cyan-400 font-semibold mt-0.5">
                {template.badge}
              </span>
              <span className="text-[11px] text-slate-400 font-normal mt-1 leading-snug">
                {template.description}
              </span>
            </div>
          </button>
        ))}
      </div>
    </div>
  )
}
